### ISSUE TITLE
Set ncnr data source to ncnr DOI root

### ISSUE THREAD

**Issue by pkienzle** [reflectometry/reduction#19]
The ncnr data DOI (http://dx.doi.org/10.18434/T4201B) points to the ncnr data directory not the parent pub directory.  Suggest putting this directory as the data path in reflweb config so that paths in the stored templates are relative to the DOI.
```
data_sources = {
    "ncnr": "http://ncnr.nist.gov/pub/ncnrdata",
    "local": "file:///"
}
```

**Comment by bmaranville** [comment]
This is painful and my own fault.  I chose "pub" as the root of the "ncnr" data repo before working with the DOI pointer.  I have implemented and pushed a DOI version of the data source, and I am considering making it the default, but it is not backwards compatible because the root directory is different and the paths from old reductions will all be wrong.  So we have to keep "ncnr" around as a data source, while adding "ncnr_DOI"
